title: bholaCodeCamp
description: At bholaCodeCamp, I'm dedicated to helping developers at all levels enhance their skills and advance their careers. My tutorials, resources, and community are designed to support your learning journey.

url: https://rajeshbhola.github.io/
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
#plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Blogs
      url: /blogs

social:
    github: rajeshbhola?tab=repositories
    twitter: therajeshbhola
    youtube: bholarajesh

google_analytics: "UA-58263416-1"
icons: 
    - fas fa-home 
    - fas fa-user 
    - fab fa-blogger-b

plugins:
  - jekyll-toc
  - jekyll-paginate
  - jekyll-sitemap

toc:
  min_level: 1
  max_level: 3
  list_class: toc
  sublist_class: toc__sublist
